name: consciousnutrishift.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.893581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#3f7858'
    - '#a6fa9e'
    - '#5c9eda'
    - '#8bd087'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
