analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 1
  lightness: 0.514358
  rhythmicContrast: 0.493243
  saturation: 0.53125
cta: {}
layout_spectrum: 1
name: consciousnutrishift.com
opengraph: {}
purpose: []
typography_spectrum: 1
