name: consciousnutrishift.com
favicon: null
layout_spectrum: 0.75181
typography_spectrum: 0.28292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#053946'
    - '#a7cde4'
    - '#309fe4'
    - '#579032'
    - '#ecf8f8'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
