analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 1
  lightness: 0.754223
  rhythmicContrast: 0.510978
  saturation: 0.754223
cta: {}
layout_spectrum: 1
name: consciousnutrishift.com
opengraph: {}
purpose: []
typography_spectrum: 0.893581
